server:
  port: 8289

network: mainnet

chains: [Bitcoin, Dash, BitcoinCash, Litecoin]

walletnode:
  btc:
    rpc_url: 'nd-314-634-477.p2pify.com'
    rpc_user: 'lucid-swanson'
    rpc_pass: 'salon-ahead-vanish-dial-curdle-arise'
    data_api_url: 'https://www.oklink.com/'
    data_api_key: '5181d535-b68f-41cf-bbc6-25905e46b6a6'
    data_api_token: ''
    time_out: 100
    tp_api_url: 'https://blockchain.info/'
  dash:
    rpc_url: 'go.getblock.io/1b8c3b32d56844e69d03139b0ef4ec6f'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://www.oklink.com/'
    data_api_key: '5181d535-b68f-41cf-bbc6-25905e46b6a6'
    data_api_token: ''
    time_out: 100
    tp_api_url: ''
  bch:
    rpc_url: 'go.getblock.io/1b8c3b32d56844e69d03139b0ef4ec6f'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://www.oklink.com/'
    data_api_key: '5181d535-b68f-41cf-bbc6-25905e46b6a6'
    data_api_token: ''
    time_out: 100
    tp_api_url: ''
  ltc:
    rpc_url: 'https://go.getblock.io/89cbf02d3e5d4a509e660c9d5215a336'
    rpc_user: ''
    rpc_pass: ''
    data_api_url: 'https://www.oklink.com/'
    data_api_key: '5181d535-b68f-41cf-bbc6-25905e46b6a6'
    data_api_token: ''
    time_out: 100
    tp_api_url: 'https://blockchain.info/'


